apiVersion: v1
kind: Service
metadata:
  name: public-openresty
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: public-openresty
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-openresty
spec:
  replicas: 2
  selector:
    matchLabels:
      app: public-openresty
  template:
    metadata:
      labels:
        app: public-openresty
    spec:
      volumes:
        - name: public-openresty-nginx-conf
          configMap:
            name: public-openresty-nginx-conf
            defaultMode: 420
        - name: public-openresty-nginx-lua
          configMap:
            name: public-openresty-nginx-lua
            defaultMode: 420
        - name: public-openresty-nginx-confd
          configMap:
            name: public-openresty-nginx-confd
            defaultMode: 420
        - name: public-openresty-nginx-cropid
          configMap:
            name: public-openresty-nginx-cropid
            defaultMode: 420
      containers:
        - name: gin-proxy
          image: gin-proxy:2024-10-17-14-05-58
          command:
            - proxy
          args:
            - '-port=8080'
            - '-redis_addr=redis:6379'
            - '-redis_pw=pwd'
            - '-redis_db=3'
            - '-before_upStream=http://'
            - '-after_upStream=.<命名空间>.svc.cluster.local:20000'
            - '-log_mode=release'
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: public-openresty-nginx-cropid
              mountPath: /app/gin_conf
          readinessProbe:
            httpGet:
              path: /check_gin_proxy
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 30
          lifecycle:
            preStop:
              exec:
                command:
                  - sleep 20
        - name: openresty
          image: openresty
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          env:
            - name: TZ
              value: Asia/Shanghai
          resources: {}
          volumeMounts:
            - name: public-openresty-nginx-conf
              mountPath: /usr/local/openresty/nginx/conf/nginx.conf
              subPath: nginx.conf
            - name: public-openresty-nginx-lua
              mountPath: /usr/local/openresty/nginx/lua
            - name: public-openresty-nginx-confd
              mountPath: /usr/local/openresty/nginx/conf/conf.d
            - name: public-openresty-nginx-cropid
              mountPath: /usr/local/openresty/nginx/cropid
          readinessProbe:
            httpGet:
              path: /health
              port: 80
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /check_gin_proxy
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 30
          lifecycle:
            preStop:
              exec:
                command:
                  - sleep 20
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 25%
  minReadySeconds: 20